import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#f0f1f1",
        "secondary-container": "#316bf3",
        "surface-tint": "#5f5e5e",
        "outline-variant": "#c4c7c7",
        "tertiary": "#000000",
        "surface-container-highest": "#e2e2e2",
        "on-surface-variant": "#444748",
        "on-secondary-container": "#fefcff",
        "on-tertiary-fixed-variant": "#3c475a",
        "primary": "#000000",
        "surface": "#f9f9f9",
        "primary-fixed-dim": "#c8c6c5",
        "surface-container-high": "#e8e8e8",
        "primary-container": "#1c1b1b",
        "tertiary-container": "#111c2d",
        "surface-dim": "#dadada",
        "secondary-fixed-dim": "#b4c5ff",
        "primary-fixed": "#e5e2e1",
        "inverse-surface": "#2f3131",
        "outline": "#747878",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#1a1c1c",
        "on-primary-container": "#858383",
        "surface-container": "#eeeeee",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e2e2e2",
        "background": "#ffffff",
        "on-error": "#ffffff",
        "on-primary-fixed": "#1c1b1b",
        "on-tertiary-fixed": "#111c2d",
        "on-primary": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "on-primary-fixed-variant": "#474646",
        "on-tertiary-container": "#79849a",
        "tertiary-fixed": "#d8e3fb",
        "surface-bright": "#f9f9f9",
        "secondary-fixed": "#dbe1ff",
        "inverse-primary": "#c8c6c5",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#00174b",
        "error-container": "#ffdad6",
        "on-background": "#1a1c1c",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#bcc7de",
        "on-secondary-fixed-variant": "#003ea8",
        "secondary": "#0051d5",
        "error": "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        xs: "4px",
        "margin-mobile": "16px",
        gutter: "24px",
        "margin-desktop": "32px",
        md: "16px",
        unit: "4px",
        xl: "48px",
        lg: "24px",
        sm: "8px",
      },
      fontFamily: {
        "label-md": ["JetBrains Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "headline-sm": ["Outfit", "sans-serif"],
        "headline-lg-mobile": ["Outfit", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"],
        display: ["Outfit", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-md": [
          "12px",
          { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "500" },
        ],
        "label-sm": [
          "10px",
          { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "headline-sm": ["18px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "1.2", fontWeight: "600" },
        ],
        "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "headline-lg": [
          "32px",
          {
            lineHeight: "1.2",
            letterSpacing: "-0.01em",
            fontWeight: "500",
          },
        ],
        display: [
          "48px",
          {
            lineHeight: "1.1",
            letterSpacing: "-0.02em",
            fontWeight: "600",
          },
        ],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
