"use client";

import { useState } from "react";

import { GraphNode } from "../lib/graph-helpers";
import { useWalrusBlob } from "../hooks/useWalrusBlob";

interface NodeDetailPanelProps {
  node: GraphNode | null;
  isOpen: boolean;
  onClose: () => void;
  onFocus: () => void;
}

export default function NodeDetailPanel({ node, isOpen, onClose, onFocus }: NodeDetailPanelProps) {
  const [copiedId, setCopiedId] = useState<string | null>(null);

  // Fetch blob data if a node is selected
  const { content, loading, error } = useWalrusBlob(node?.blobId || null);

  // Helper to determine node type text and color
  const getNodeTypeInfo = (depth: number, nodeType: number) => {
    if (depth === 0) return { label: "Topic Root", color: "bg-slate-800" };
    switch (nodeType) {
      case 0: return { label: "Contribution", color: "bg-blue-600" };
      case 1: return { label: "Challenge", color: "bg-red-600" };
      case 2: return { label: "Refinement", color: "bg-teal-600" };
      case 3: return { label: "Synthesis", color: "bg-green-600" };
      default: return { label: "Unknown", color: "bg-gray-500" };
    }
  };

  const copyToClipboard = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  return (
    <aside
      id="rightPanel"
      className={`
        w-full xl:w-96 flex-shrink-0 bg-surface-container-lowest border-hairline-l
        flex flex-col z-40 absolute inset-y-0 right-0 xl:relative
        transition-transform duration-300 shadow-[-4px_0_24px_rgba(0,0,0,0.05)] xl:shadow-none
        transition-cubic
        ${isOpen ? "translate-x-0" : "translate-x-full xl:translate-x-0"}
      `}
    >
      {/* Panel Header */}
      <div className="p-md border-hairline-b flex items-center justify-between bg-surface-bright">
        <div className="flex items-center gap-sm">
          <div className="w-3 h-3 rounded-full bg-primary" />
          <h2 className="font-headline-sm text-headline-sm text-primary font-headline-md">
            Node Inspector
          </h2>
        </div>
        <button
          className="xl:hidden p-xs rounded-full hover:bg-surface-container transition-cubic"
          onClick={onClose}
        >
          <span className="material-symbols-outlined text-[20px]">close</span>
        </button>
      </div>

      {!node ? (
        <div className="flex-1 flex items-center justify-center p-md text-on-surface-variant font-body-md">
          Select a node in the graph to view details.
        </div>
      ) : (
        <div className="flex-1 overflow-y-auto p-gutter flex flex-col gap-xl">
          {/* Node Metadata Header */}
          <div>
            <span className="font-label-sm text-label-sm uppercase tracking-widest text-outline bg-surface-container-low px-2 py-1 rounded inline-block mb-2 font-label-md">
              Node Type
            </span>
            <div className="flex items-center gap-2 mb-2">
              <div className={`w-3 h-3 rounded-full ${getNodeTypeInfo(node.depth, node.nodeType).color}`} />
              <h3 className="font-headline-md text-headline-md text-primary font-medium font-headline-lg-mobile">
                {getNodeTypeInfo(node.depth, node.nodeType).label}
              </h3>
            </div>
            <p className="font-body-md text-body-md text-on-surface-variant font-body-lg">
              Generated by Agent: <span className="font-mono text-primary text-sm">{node.agentAddress.substring(0, 8)}...</span>
            </p>
          </div>

          {/* Properties Grid */}
          <div className="grid grid-cols-1 gap-y-md border-t border-hairline pt-md">
            {/* Object ID */}
            <div className="flex flex-col gap-xs">
              <span className="font-label-sm text-label-sm text-outline uppercase tracking-widest font-label-md">
                Sui Object ID
              </span>
              <div className="flex items-center justify-between bg-[#fafafa] border-hairline p-2 rounded transition-cubic hover:border-outline-variant">
                <span className="font-label-md text-label-md text-primary font-mono truncate mr-2 text-[14px]">
                  {node.id}
                </span>
                <button
                  className={`text-outline transition-cubic flex-shrink-0 ${copiedId === 'object' ? 'text-green-500' : 'hover:text-primary'}`}
                  onClick={() => copyToClipboard(node.id, 'object')}
                  title="Copy ID"
                >
                  <span className="material-symbols-outlined text-[16px]">
                    {copiedId === 'object' ? 'check' : 'content_copy'}
                  </span>
                </button>
              </div>
            </div>

            {/* Blob ID */}
            <div className="flex flex-col gap-xs">
              <span className="font-label-sm text-label-sm text-outline uppercase tracking-widest font-label-md">
                Walrus Blob ID
              </span>
              <div className="flex items-center justify-between bg-[#fafafa] border-hairline p-2 rounded transition-cubic hover:border-outline-variant">
                <span className="font-label-md text-label-md text-primary font-mono truncate mr-2 text-[14px]">
                  {node.blobId || "None"}
                </span>
                {node.blobId && (
                  <button
                    className={`text-outline transition-cubic flex-shrink-0 ${copiedId === 'blob' ? 'text-green-500' : 'hover:text-primary'}`}
                    onClick={() => copyToClipboard(node.blobId, 'blob')}
                    title="Copy Blob ID"
                  >
                    <span className="material-symbols-outlined text-[16px]">
                      {copiedId === 'blob' ? 'check' : 'content_copy'}
                    </span>
                  </button>
                )}
              </div>
            </div>

            {/* Depth & Model */}
            <div className="grid grid-cols-2 gap-md">
              <div className="flex flex-col gap-xs">
                <span className="font-label-sm text-label-sm text-outline uppercase tracking-widest font-label-md">
                  Depth
                </span>
                <span className="font-body-md text-primary font-mono">{node.depth}</span>
              </div>
              <div className="flex flex-col gap-xs">
                <span className="font-label-sm text-label-sm text-outline uppercase tracking-widest font-label-md">
                  Model
                </span>
                <span className="font-body-md text-primary font-mono">
                  {node.modelName || "N/A"}
                </span>
              </div>
            </div>
          </div>

          {/* Blob Content */}
          <div className="flex flex-col gap-sm">
            <div className="flex items-center justify-between">
              <span className="font-label-sm text-label-sm text-outline uppercase tracking-widest font-label-md">
                Extracted Content
              </span>
              <span className="font-label-sm text-label-sm text-primary bg-surface-container px-2 py-0.5 rounded font-label-md">
                Raw Text
              </span>
            </div>
            
            <div className="bg-[#fafafa] border-hairline p-md rounded transition-cubic hover:border-outline-variant relative min-h-[150px]">
              {loading && (
                <div className="absolute inset-0 flex items-center justify-center bg-[#fafafa]/80">
                  <span className="material-symbols-outlined indicator-pulse text-outline text-3xl">hourglass_empty</span>
                </div>
              )}
              {error && (
                <div className="text-on-surface-variant italic font-label-md text-label-md">
                  Content stored on Walrus (testnet blob may have expired)
                </div>
              )}
              {!loading && !error && !content && node.depth === 0 && (
                <div className="text-on-surface-variant italic font-label-md text-label-md">
                  Root node has no attached blob.
                </div>
              )}
              {!loading && !error && content && (
                <pre className="font-label-md text-[13px] text-on-surface overflow-x-auto whitespace-pre-wrap break-words leading-relaxed">
                  {content}
                </pre>
              )}
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex flex-col gap-sm mt-auto pt-md border-t border-hairline">
            <button
              className="w-full bg-primary text-on-primary font-label-md text-label-md uppercase tracking-widest py-3 border border-primary hover:bg-[#222222] transition-cubic"
              onClick={() => window.open(`https://suiscan.xyz/testnet/object/${node.id}`, "_blank")}
            >
              View on Sui Explorer
            </button>
            <button
              className="w-full bg-surface-container text-primary font-label-md text-label-md uppercase tracking-widest py-3 border-hairline hover:bg-surface-container-low transition-cubic disabled:opacity-50 border"
              disabled={!node.blobId}
              onClick={() => window.open(`https://aggregator.walrus-testnet.walrus.space/v1/blobs/${node.blobId}`, "_blank")}
            >
              View on Walrus Explorer
            </button>
            <button 
              className="w-full bg-surface-container text-primary font-label-md text-label-md uppercase tracking-widest py-3 border-hairline hover:bg-surface-container-low transition-cubic border"
              onClick={onFocus}
            >
              Focus Node in Graph
            </button>
          </div>
        </div>
      )}
    </aside>
  );
}
